### ISSUE TITLE
주제 선정

### ISSUE THREAD

**Issue by Saon227** [Saon227/CRUD_mini_project#1]
저희 주제 뭘로 할까요??

**Comment by sijinp0** [comment]
관리 할 주제가 뭐가 있을까요?

**Comment by Saon227** [comment]
학교 관련된 것도 괜찮을 것 같고, 사실 어떤 걸 해도 CRUD랑 관리 기능은 있을 것 같아서
하고 싶은 주제 있으면 하면 될 것 같아요!

**Comment by Saon227** [comment]
하고 싶은 거 있으세요?

**Comment by Saon227** [comment]
시간표도 괜찮을 것 같아요

**Comment by sijinp0** [comment]
수업명 학점 점수매기기 전공/교양

**Comment by Saon227** [comment]
좋아요!

**Comment by Saon227** [comment]
주제
-> 시간표 관리 로 할게요
