### ISSUE TITLE
함수 설계

### ISSUE THREAD

**Issue by Saon227** [Saon227/CRUD_mini_project#4]

**Comment by sijinp0** [comment]
CRUD
List
FIle S/L
Search 3

**Comment by Saon227** [comment]
Create
Read
Update
Delete
List
Save
Load
Search1
Search2
Search3

이렇게 하면 딱 10개네요

**Comment by Saon227** [comment]
구조체도 만들어야 합니당

**Comment by Saon227** [comment]
들어가는 데이터를 어떤 걸로 할까요

**Comment by sijinp0** [comment]
수업명 
학점 
점수매기기
전공/교양
이면 될 것 같아요

**Comment by Saon227** [comment]
그러면 제가 구조체 설계를 하겠습니다!

**Comment by Saon227** [comment]
함수 정의 부탁드려도 될까요?

**Comment by sijinp0** [comment]
네

**Comment by Saon227** [comment]
typedef struct {
    char name[20];  // 수업명
    char profname[20];  // 교수님 성함
    float credit;  // 학점
    int grade_type;  // 성적 유형 : 1이면 그레이드, 2면 pf
} Class;

**Comment by Saon227** [comment]
typedef struct {
    char name[20];  // 수업명
    char profname[20];  // 교수님 성함
    float credit;  // 학점
    int period; // 교시
} Class;

**Comment by sijinp0** [comment]
void listClass(Class *c, int count);

int selectDataNo(Class *c, int count);

int addClass(Class *c);

void readClass(Class c);

int updateClass(Class *c);

int deleteClass(Class *c);

void saveData(Class *c, int count);

int loadData(Class *c);

void searchClass(Class *c, int count);

void searchProf(Class *c, int count);

void searchCredit(Class *c, int count);
