### ISSUE TITLE
Readme작성

### ISSUE THREAD

**Issue by sijinp0** [Saon227/CRUD_mini_project#6]

**Comment by sijinp0** [comment]
뭐가 들어가나요?

**Comment by Saon227** [comment]
주제
대략적인 기능 설명
팀소개
역할

이렇게 적으면 될 것 같아요

**Comment by Saon227** [comment]
주제는 시긴표 관리 프로젝트이고
기능 설명은 아까 설계한 함수 설명하면 될 것 같고
팀원 이름이랑 역할 분담은 아까 정한대로 적으면 될 것 같아요

**Comment by sijinp0** [comment]
C (Create) : 수강하는 과목을 추가하는 기능
R (Read) : 추가된 과목을 조회하는 기능
U (Update) : 추가된 과목의 내용을 수정하는 기능
D (Delete) : 추가된 과목을 삭제하는 기능
저장 : 변경된 내용을 파일에 저장하는 기능
불러오기 : 파일에 저장되어 있는 데이터를 불러오는 기능
검색(수업) : 수업명으로 검색하는 기능
검색(교수님) :교수명으로 검색하는 기능
검색(학점) : 학점으로 검색하는 기능

**Comment by Saon227** [comment]
주제
시간표 관리

대략적인 기능 설명
C (Create) : 수강하는 과목을 추가하는 기능
R (Read) : 추가된 과목을 조회하는 기능
U (Update) : 추가된 과목의 내용을 수정하는 기능
D (Delete) : 추가된 과목을 삭제하는 기능
저장 : 변경된 내용을 파일에 저장하는 기능
불러오기 : 파일에 저장되어 있는 데이터를 불러오는 기능
검색(수업) : 수업명으로 검색하는 기능
검색(교수님) :교수명으로 검색하는 기능
검색(학점) : 학점으로 검색하는 기능

팀소개
안녕하세요 저희는 오픈소스 소프트웨어 실습을 수강 중인 김고은, 박시진입니다.
저희 팀의 주제는 시간표를 저장하고 불러오고 검색할 수 있는 프로젝트입니다.
또한 이를 통해 GitHub와 git을 능숙하게 사용할 수 있게 되는 것이 저희 팀의 목표입니다.

팀원 및 역할
22000050 김고은
-> 구조체 정의, 위키 작성
22000274 박시진
-> 함수 정의, 기능 설명
같이 하는 것
-> README 파일 작성, 함수 구현
