### ISSUE TITLE
할일

### ISSUE THREAD

**Issue by Saon227** [Saon227/CRUD_mini_project#8]
1. 검색 기능 및 파일 저장, 읽어보기 기능을 제외한 모든 함수 구현 및 git으로 버전 관리
2. 완성된 각 함수를 실행한 화면캡처 업로드 (github repository root에서 /screenshots 폴더 만들어서 이미지 업로드)
3. issue를 사용하여 개발에 필요한 의견 교환
4. WIKI에서 완성된 함수 설명 및 결과 이미지를 이용한 페이지 추가(md 페이지 추가)

**Comment by Saon227** [comment]
우선 
void listClass(Class *c, int count);
int selectDataNo(Class *c, int count);
int addClass(Class *c);
void readClass(Class c);
int updateClass(Class *c);
int deleteClass(Class *c);
이 함수들을 구현하면 될 것 같아요

**Comment by Saon227** [comment]
구조체는 선언한 대로 사용하고, 

int addClass(Class *c);
void readClass(Class c);
void listClass(Class *c, int count)

를 한 명이 하고, 나머지 한 명이

int selectDataNo(Class *c, int count);
int updateClass(Class *c);
int deleteClass(Class *c);

이거를 하면 될 것 같아요!

**Comment by Saon227** [comment]
함수 하나 완성 될 때마다 실행해보고 화면캡쳐해서 올려주세요!

**Comment by Saon227** [comment]
제가 오늘 중으로 기본적인 틀이랑
int addClass(Class *c);
void readClass(Class c);
void listClass(Class *c, int count)

이 세가지 해놓겠습니다.

학우님이 나머지 세개 하시고 
/screenshots 폴더에 캡쳐 올리고 PR 보내주세요

**Comment by Saon227** [comment]
혹시 괜찮으시다면

int addClass(Class *c);
void readClass(Class c);
void listClass(Class *c, int count)

이 세 가지 구현 먼저 부탁드려도 될까요?
함수 구현이랑 /screenshots 폴더에 캡쳐 올리고 PR 보내주시면 됩니다!

**Comment by Saon227** [comment]
제가 토요일 이후에 시간이 돼서 그 때 나머지 하겠습니다

**Comment by sijinp0** [comment]
pr 올렸습니다

**Comment by sijinp0** [comment]
int main(){
    int count = 0;
    int result = 0;
    Class clist[20];
    int index =0;
    count += addClass(&clist[index++]);
    printf("번호   수업  교수님  학점  교시\n");
    for(int i =0; i <count ; i++){
        if(clist[i].credit == 0){
            continue;
        }
        printf("%2d ", i+1);
        readClass(clist[i]);
    }
    printf("\n");
    updateClass(&clist[index-1]);
    for(int i =0; i <count ; i++){
        if(clist[i].credit == 0){ 
            continue;
        }
        printf("%2d ", i+1);
        readClass(clist[i]);
    } 
    return 0;
}

**Comment by sijinp0** [comment]
확인용으로 사용한 메인 함수입니다
확인하실 때 필요하시면 사용하세요

**Comment by Saon227** [comment]
감사합니다!

**Comment by Saon227** [comment]
함수 구현을 
int addClass(Class *c);   
void readClass(Class c);   
int updateClass(Class *c);
이렇게 세 개를 하셔서 제가 나머지 했습니다!

추가로 Menu랑 main.c 파일, WIKI 작성했고, main.c를 만들면서 스크린샷도 수정했습니다

**Comment by Saon227** [comment]
괜찮은지 한 번 확인해주시겠어요?
